language: c
cache:
  directories:
  - $HOME/.stack
matrix:
  include:
  - env: ARGS="--resolver lts-10.3"
    compiler: ': #stack 8.2.2'
    addons:
      apt:
        packages:
        - libgmp-dev
before_install:
- unset CC
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack -j1 --no-terminal --install-ghc $ARGS test --bench --only-dependencies
script:
- stack -j1 --no-terminal $ARGS build
- mkdir deploy-build
- mv .stack-work/install/x86_64-linux/lts-10.3/8.2.2/bin/deploy-exe
  deploy-build/
- mv .stack-work/install/x86_64-linux/lts-10.3/8.2.2/bin/deploy-init
  deploy-build/
- zip -q -r deploy-build.zip deploy-build
deploy:
  provider: releases
  api_key:
    secure: CkTA6vj9W09EZg+Z+IAJxx0eFhPTXbTCWdku+Xsqe1cMMagj5lh56pTYx0o+zLitAlyuenuGZnL3mOrU/r/uzrV6L1sREUuQ5HCyo3UiFvqsOUI9qZ+9DUeSkx420J+jPSBJfNjm0EQxsHcLyVXQ3mOo2B0oo9G67+pPYqiJb0454C26gXo6CXNU6TtJlMNyhqV7DckePek0QQGHcptdcGm/5h7m02xkkmNrto5ghbYlwwBACKxwc0H9WRcP+2lvaTXiD94HFeIcC9DU1+xrqa3Rf/FiTj7J9g3MR0Ov3fBHSLK0HrSx0mmLB4ysszkv3wGEC7rxvostP1L0punnhjU2hqzRogDHaF5ClgyTQfmxWbvVlUsRL11h9NEQtuLlZNDIT0eQ1ZNzagzuWUomv/gATUU4aJa2h4fG09rlxSBNd13wGMbkTdbssBXWgYEnOSjCTJ9w1x7C5IEIBvVuYHg/iP7mj4G8TUlGEjNAllACuIBJbRZsCgIPPRMlJpDrH7rOGSuD/7Sw8MBAhOIUnq+Knd1+fYm2KfkynfYFg4Zu8/6D+PqXya76H4MqSWdgu1P5eeP5Lits3YOSj44uZkrsvpKsP0brFcLGuHaGQih0ONkXXfSIFoNT6dVya3LTYU6tSdsN8mzRJwp4dFBqmeiyiMvYQhgFUIo2aXCU2ZA=
  file: ~/deploy-build.zip
  on:
    tags: true
    branch: 'master'
    repo: epicallan/deploy
