name: deploy
version: '0.1.12'
category: Web
author: Lukwago Allan
maintainer: epicallan.al@gmail.com
copyright: 2017 Lukwago Allan
license: BSD3
github: epicallan/deploy
extra-source-files:
- README.md
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fno-warn-orphans
  - -optl-fuse-ld=lld

ld-options: -fuse-ld=lld

default-extensions: 
- OverloadedStrings
- DataKinds
- ScopedTypeVariables
- TypeOperators
- NoImplicitPrelude 
- DeriveGeneric 
- RecordWildCards
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses

library:
  source-dirs: src
  exposed-modules:
  - Deploy.API
  - Deploy.Types
  - Deploy.Execute.Core
  - Deploy.Initiate.Core
  dependencies:
  - base >=4.7 && <5
  - protolude >= 0.2
  - text >=1.2.2.2
  - bytestring >=0.10.8.1
  - aeson
  - http-conduit
  - http-types
  - safe-exceptions
  - bytestring
  - docker >=0.4.1.1
  - directory
  - servant-multipart >=0.11
  - http-client >=0.5.7.0
  - process >=1.4.3.0
  - transformers >=0.5.2.0
  - network >=2.6.3.2
  - HaskellNet >=0.5.1
  - servant-server
  - wai
  - warp
  - ghc
  - dhall
  - unix
  - temporary
executables:
  deploy-init:
    main: Main.hs
    source-dirs: cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base
      - protolude >= 0.2
      - deploy
  deploy-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - protolude >= 0.2
    - deploy
tests:
  deploy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - deploy
