name: deploy
version: '0.1.1'
category: Web
author: Lukwago Allan
maintainer: epicallan.al@gmail.com
copyright: 2017 Lukwago Allan
license: BSD3
github: epicallan/deploy
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Deploy.API
  - Deploy.Types
  - Deploy.Execute.Core
  - Deploy.Initiate.Core
  - Deploy.Util
  dependencies:
  - base >=4.7 && <5
  - text >=1.2.2.2
  - bytestring >=0.10.8.1
  - aeson
  - http-conduit
  - http-types
  - safe-exceptions
  - exceptions
  - bytestring
  - docker >=0.4.1.1
  - directory
  - servant-multipart >=0.11
  - http-client >=0.5.7.0
  - process >=1.4.3.0
  - transformers >=0.5.2.0
  - network >=2.6.3.2
  - HaskellNet >=0.5.1
  - servant-server
  - wai
  - warp
  - mtl
executables:
  deploy-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - deploy
    - text >=1.2.2.2
tests:
  deploy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - deploy
