name: deploy
version: '0.1.12'
category: Web
author: Lukwago Allan
maintainer: epicallan.al@gmail.com
copyright: 2017 Lukwago Allan
license: BSD3
github: epicallan/deploy
extra-source-files:
- README.md
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -fno-warn-orphans

default-extensions: 
- OverloadedStrings
- DataKinds
- ScopedTypeVariables
- TypeOperators
- NoImplicitPrelude 
- DeriveGeneric 
- RecordWildCards
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses

library:
  source-dirs: src
  exposed-modules:
  - Deploy.API
  - Deploy.Types
  - Deploy.Execute
  - Deploy.Initiate
  dependencies:
  - aeson
  - base
  - blaze-builder
  - bytestring
  - dhall
  - directory
  - docker
  - ghc
  - HaskellNet 
  - http-client
  - http-conduit
  - http-types
  - network
  - process
  - protolude
  - safe-exceptions
  - scotty
  - temporary
  - text 
  - unix
  - wai
  - wai-extra
  - warp
executables:
  deploy-init:
    main: Main.hs
    source-dirs: cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base
      - deploy
      - protolude
  deploy-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - deploy
    - protolude
tests:
  deploy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - deploy
